GET http://127.0.0.1:5173/server/get_server_info

### File path acquisition
POST http://127.0.0.1:8023/path/files
Content-Type: application/json

{
"path":"D:\\code\\sinosoft\\xk"
}

### files to path
POST http://127.0.0.1:8023/backup/files
Content-Type: application/json

{
  "sourceFiles":[
    "G:\\test\\test.txt"
  ],
  "targetPath":"G:\\test1"
}
### path to path
POST http://127.0.0.1:8023/backup/path
Content-Type: application/json

{
  "sourcePath":"G:\\test\\",
  "targetPath":"G:\\test1\\"
}
