server:
  port: 8023
  servlet:
    context-path: /server-mgr
spring:
  application:
    name: ServerManager
  aop:
    proxy-target-class: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/main/resources/db/server-manager.db
# mybatis-plus logout
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
# env
env:
  bark:
    server:
      url: 101.91.225.182:30032
      keys: cemimNcdSxda2jYyBYUB9,ozzVLYa8Goe8cg3P48sNH4
      sound:  #声音
      isArchive: #自动保存通知消息，1-是
      icon: #自定义图标
      group: #对消息进行分组
      timeLiness: #时效性通知 1、active-默认值，系统会立即亮屏通知 2、timeSensitive-可在专注模式下显示通知 3、passive-仅将通知添加到通知列表，不会亮屏提醒
      level:
  servermgr:
    version: 0.1.1
logging:
  config: classpath:logback-spring.xml

# swagger2
swagger2:
  ui:
    enable: true

#mail
mail:
  receivers:
  cc:
  bcc:
  sender:
  host:
  username:
  password:
  port: 1111
