server:
  port: 8023
  servlet:
    context-path: /server-mgr
spring:
  application:
    name: ServerManager
  aop:
    proxy-target-class: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/main/resources/db/server-manager.db
# mybatis-plus logout
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
# env
env:
  bark:
    server:
      url: 101.91.225.182:30011
  servermgr:
    version: 0.1.0
logging:
  config: classpath:logback-spring.xml

# swagger2
swagger2:
  ui:
    enable: true
